[package]
name = "ihome-iot-server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.4", features = ["ws"] }
rumqttc = "0.25.0"
rumqttd = "0.20.0"
tokio = { version = "1.47.0", features = ["full"] }
config = "0.15.18"
tracing-subscriber = "0.3.20"
tracing = "0.1.41"
local-ip-address = "0.6.5"
hound = "3.5.1"
sha2 = "0.10.9"
hex = "0.4.3"
vosk = "0.3.1"
